version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: riffradar-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - riffradar-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: riffradar-backend
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    environment:
      - REDIS_URL=redis://redis:6379 
    volumes:
      - chroma_data:/app/chroma_db
      - ./src:/app/src
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - riffradar-network
    command: >
      sh -c "python src/chroma/seed_songs.py && python run.py"

volumes:
  chroma_data:
    driver: local

networks:
  riffradar-network:
    driver: bridge